version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db_kitty:
    image: postgres:13.10
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    restart: always
    env_file: .env
    depends_on:
      - db_kitty
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    build: ./nginx/
    env_file: .env
    restart: always
    ports:
      - $NGINX_PORT:80
    volumes:
      - static:/static
      - media:/media