version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db_kitty:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
#    build: ./backend/
    image: maniac82/kittygram_backend
    env_file: .env
    depends_on:
      - db_kitty
    volumes:
      - static:/backend_static

  frontend:
    env_file: .env
#    build: ./frontend/
    image: maniac82/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
#    build: ./nginx/
    image: maniac82/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media
